=== PatinhoGamer/ID/contratos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="contratos">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="municipio" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="contrato" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="objetoContrato" type="xs:string" />
                              <xs:element name="preco" type="xs:string" />
                              <xs:element name="publicacao">
                                 <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                       <xs:pattern value="\d{1,2}-\d{1,2}-\d{4}" />
                                    </xs:restriction>
                                 </xs:simpleType>
                              </xs:element>
                              <xs:element name="adjudicatario" type="xs:string" />
                           </xs:sequence>
                           <xs:attribute name="id" type="xs:string" use="required" />
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="nomeMun" type="xs:string" use="required" />
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== PatinhoGamer/ID/contratos.xml
<?xml version="1.0" encoding="utf-8"?>
<contratos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contratos.xsd">
	<municipio nomeMun="Arganil" />
	<municipio nomeMun="Cantanhede" />
	<municipio nomeMun="Coimbra" />
	<municipio nomeMun="Condeixa-a-Nova" />
	<municipio nomeMun="Figueira da Foz" />
	<municipio nomeMun="Góis" />
	<municipio nomeMun="Lousã" />
	<municipio nomeMun="Mira" />
	<municipio nomeMun="Miranda do Corvo" />
	<municipio nomeMun="Montemor-o-Velho" />
	<municipio nomeMun="Oliveira do Hospital" />
	<municipio nomeMun="Pampilhosa da Serra" />
	<municipio nomeMun="Penacova" />
	<municipio nomeMun="Penela" />
	<municipio nomeMun="Soure" />
	<municipio nomeMun="Tábua" />
	<municipio nomeMun="Vila Nova de Poiares" />
</contratos>
